### ISSUE TITLE
inMap实例化出错

### ISSUE THREAD

**Issue by chenli8** [TalkingData/inmap#13]
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at e.value (http://localhost:8080/dist/0.chunk.js:107:119623)
    at Object.td_0_msgId_2 (http://localhost:8080/dist/0.chunk.js:107:119259)
    at Worker.value (http://localhost:8080/dist/0.chunk.js:107:102605)

**Comment by fengluhome** [comment]
地图容器没有设置div高度造成的
 <div id="allmap" style="height:500px;"></div>
